/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicio4;

/**
 *
 * @author fehig
 */
public class TelaLuta extends javax.swing.JFrame {

    /**
     * Creates new form TelaLutador
     */
    private Lutador lutador1,
            lutador2;

    private Boolean lutadoresVivos;

    public TelaLuta() {
        initComponents();

        pbarVidaLutador1.setValue(100);
        pbarVidaLutador2.setValue(100);
        lutador1 = new Lutador();
        lutador2 = new Lutador();
        lutadoresVivos = lutador1.getVida() > 0 && lutador2.getVida() > 0;
    }

    public void verificaVida() {
        lutadoresVivos = lutador1.getVida() > 0 && lutador2.getVida() > 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        pbarVidaLutador1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnApanharLutador1 = new javax.swing.JButton();
        btnConcentrarLutador1 = new javax.swing.JButton();
        btnApanharLutador2 = new javax.swing.JButton();
        btnConcentrarLutador2 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        pbarVidaLutador2 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pbarVidaLutador1.setBackground(new java.awt.Color(0, 255, 51));
        pbarVidaLutador1.setForeground(new java.awt.Color(0, 0, 0));
        pbarVidaLutador1.setStringPainted(true);

        jLabel1.setText("Lutador 1");

        jLabel2.setText("Lutador 2");

        btnApanharLutador1.setText("Apanhar");
        btnApanharLutador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharLutador1ActionPerformed(evt);
            }
        });

        btnConcentrarLutador1.setText("Concentrar forçar");
        btnConcentrarLutador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarLutador1ActionPerformed(evt);
            }
        });

        btnApanharLutador2.setText("Apanhar");
        btnApanharLutador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharLutador2ActionPerformed(evt);
            }
        });

        btnConcentrarLutador2.setText("Concentrar forçar");
        btnConcentrarLutador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarLutador2ActionPerformed(evt);
            }
        });

        lblResultado.setText("  ");

        pbarVidaLutador2.setBackground(new java.awt.Color(0, 255, 51));
        pbarVidaLutador2.setForeground(new java.awt.Color(0, 0, 0));
        pbarVidaLutador2.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConcentrarLutador1)
                            .addComponent(btnApanharLutador1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConcentrarLutador2)
                            .addComponent(btnApanharLutador2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbarVidaLutador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(pbarVidaLutador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarVidaLutador1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbarVidaLutador2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApanharLutador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConcentrarLutador1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApanharLutador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConcentrarLutador2)))
                .addGap(37, 37, 37)
                .addComponent(lblResultado)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApanharLutador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharLutador1ActionPerformed
        verificaVida();
        if (lutadoresVivos) {
            lutador1.apanhar();
            pbarVidaLutador1.setValue(lutador1.getVida());

            if (lutador1.getVida() <= 0) {
                lblResultado.setText("Lutador1 perdeu");
            }

        }
    }//GEN-LAST:event_btnApanharLutador1ActionPerformed

    private void btnConcentrarLutador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarLutador1ActionPerformed
        verificaVida();
        if (lutadoresVivos) {
            lutador1.concentrarForca();
            pbarVidaLutador1.setValue(lutador1.getVida());
        }
    }//GEN-LAST:event_btnConcentrarLutador1ActionPerformed

    private void btnApanharLutador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharLutador2ActionPerformed
        verificaVida();
        if (lutadoresVivos) {
            lutador2.apanhar();
            pbarVidaLutador2.setValue(lutador2.getVida());

            if (lutador2.getVida() <= 0) {
                lblResultado.setText("Lutador2 perdeu");
            }
        }
    }//GEN-LAST:event_btnApanharLutador2ActionPerformed

    private void btnConcentrarLutador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarLutador2ActionPerformed
        verificaVida();
        if (lutadoresVivos) {
            lutador2.concentrarForca();
            pbarVidaLutador2.setValue(lutador2.getVida());
        }
    }//GEN-LAST:event_btnConcentrarLutador2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApanharLutador1;
    private javax.swing.JButton btnApanharLutador2;
    private javax.swing.JButton btnConcentrarLutador1;
    private javax.swing.JButton btnConcentrarLutador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JProgressBar pbarVidaLutador1;
    private javax.swing.JProgressBar pbarVidaLutador2;
    // End of variables declaration//GEN-END:variables
}
