/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicio3;

/**
 *
 * @author fehig
 */
public class TelaElevador extends javax.swing.JFrame {

    Elevador elevador1;
    Elevador elevador2;

    /**
     * Creates new form TelaElevador
     */
    public TelaElevador() {
        initComponents();
        elevador1 = new Elevador();
        elevador2 = new Elevador();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrarMulher2 = new javax.swing.JButton();
        btnEntrarHomem1 = new javax.swing.JButton();
        btnEntrarCrianca1 = new javax.swing.JButton();
        lblTotalPassageiros1 = new javax.swing.JLabel();
        lblElevador = new javax.swing.JLabel();
        lblPesoTotal1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEntrarHomem2 = new javax.swing.JButton();
        btnEntrarMulher1 = new javax.swing.JButton();
        btnEntrarCrianca2 = new javax.swing.JButton();
        lblTotalPassageiros2 = new javax.swing.JLabel();
        lblPesoTotal2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntrarMulher2.setText("Entrar mulher");
        btnEntrarMulher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarMulher2ActionPerformed(evt);
            }
        });

        btnEntrarHomem1.setText("Entrar homem");
        btnEntrarHomem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHomem1ActionPerformed(evt);
            }
        });

        btnEntrarCrianca1.setText("Entrar criança");
        btnEntrarCrianca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCrianca1ActionPerformed(evt);
            }
        });

        lblTotalPassageiros1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalPassageiros1.setText("Total de passageiros: 0");
        lblTotalPassageiros1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblElevador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElevador.setText("Elevador 1");
        lblElevador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPesoTotal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPesoTotal1.setText("Peso total: 0 kg");
        lblPesoTotal1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elevador 2");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnEntrarHomem2.setText("Entrar homem");
        btnEntrarHomem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHomem2ActionPerformed(evt);
            }
        });

        btnEntrarMulher1.setText("Entrar mulher");
        btnEntrarMulher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarMulher1ActionPerformed(evt);
            }
        });

        btnEntrarCrianca2.setText("Entrar criança");
        btnEntrarCrianca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCrianca2ActionPerformed(evt);
            }
        });

        lblTotalPassageiros2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalPassageiros2.setText("Total de passageiros: 0");
        lblTotalPassageiros2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPesoTotal2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPesoTotal2.setText("Peso total: 0 kg");
        lblPesoTotal2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnEntrarMulher1)
                                            .addComponent(btnEntrarMulher2)))
                                    .addComponent(btnEntrarHomem2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnEntrarCrianca2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEntrarHomem1)
                                    .addComponent(lblTotalPassageiros1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEntrarCrianca1)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesoTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPassageiros2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(163, Short.MAX_VALUE)
                    .addComponent(lblElevador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(149, 149, 149)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarCrianca1)
                    .addComponent(btnEntrarHomem1)
                    .addComponent(btnEntrarMulher1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPassageiros1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesoTotal1)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarHomem2)
                    .addComponent(btnEntrarMulher2)
                    .addComponent(btnEntrarCrianca2))
                .addGap(18, 18, 18)
                .addComponent(lblTotalPassageiros2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesoTotal2)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblElevador)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarHomem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHomem1ActionPerformed
        elevador1.entrarPessoa("homem");
        lblTotalPassageiros1.setText("Total de passageiros: " + elevador1.getTotalPassageiros());
        lblPesoTotal1.setText("Peso total: " + elevador1.getPesoTotal() + "kg");
    }//GEN-LAST:event_btnEntrarHomem1ActionPerformed

    private void btnEntrarMulher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarMulher2ActionPerformed
        elevador2.entrarPessoa("mulher");
        lblTotalPassageiros2.setText("Total de passageiros: " + elevador2.getTotalPassageiros());
        lblPesoTotal2.setText("Peso total: " + elevador2.getPesoTotal() + "kg");
    }//GEN-LAST:event_btnEntrarMulher2ActionPerformed

    private void btnEntrarHomem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHomem2ActionPerformed
        elevador2.entrarPessoa("homem");
        lblTotalPassageiros2.setText("Total de passageiros: " + elevador2.getTotalPassageiros());
        lblPesoTotal2.setText("Peso total: " + elevador2.getPesoTotal() + "kg");
    }//GEN-LAST:event_btnEntrarHomem2ActionPerformed

    private void btnEntrarMulher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarMulher1ActionPerformed
        elevador1.entrarPessoa("mulher");
        lblTotalPassageiros1.setText("Total de passageiros: " + elevador1.getTotalPassageiros());
        lblPesoTotal1.setText("Peso total: " + elevador1.getPesoTotal() + "kg");
    }//GEN-LAST:event_btnEntrarMulher1ActionPerformed

    private void btnEntrarCrianca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCrianca1ActionPerformed
        elevador1.entrarPessoa("criança");
        lblTotalPassageiros1.setText("Total de passageiros: " + elevador1.getTotalPassageiros());
        lblPesoTotal1.setText("Peso total: " + elevador1.getPesoTotal() + "kg");        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarCrianca1ActionPerformed

    private void btnEntrarCrianca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCrianca2ActionPerformed
        elevador2.entrarPessoa("criança");
        lblTotalPassageiros2.setText("Total de passageiros: " + elevador2.getTotalPassageiros());
        lblPesoTotal2.setText("Peso total: " + elevador2.getPesoTotal() + "kg");
    }//GEN-LAST:event_btnEntrarCrianca2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaElevador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarCrianca1;
    private javax.swing.JButton btnEntrarCrianca2;
    private javax.swing.JButton btnEntrarHomem1;
    private javax.swing.JButton btnEntrarHomem2;
    private javax.swing.JButton btnEntrarMulher1;
    private javax.swing.JButton btnEntrarMulher2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblElevador;
    private javax.swing.JLabel lblPesoTotal1;
    private javax.swing.JLabel lblPesoTotal2;
    private javax.swing.JLabel lblTotalPassageiros1;
    private javax.swing.JLabel lblTotalPassageiros2;
    // End of variables declaration//GEN-END:variables
}
