/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicio2;

/**
 *
 * @author fehig
 */
public class TelaDadinho extends javax.swing.JFrame {
    Dadinho dadinho1;
    Dadinho dadinho2;
    Integer vitoriasDadinho1;
    Integer vitoriasDadinho2;
    
    
    /**
     * Creates new form TelaDadinho
     */
    // Construtor
    public TelaDadinho() {
        initComponents();
        dadinho1 = new Dadinho();
        dadinho2 = new Dadinho();
        vitoriasDadinho1 = 0;
        vitoriasDadinho2 = 0;               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSortearDadinho = new javax.swing.JButton();
        lblDadinho1 = new javax.swing.JLabel();
        lblDadinho2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblVitoriasDadinho1 = new javax.swing.JLabel();
        lblVitoriasDadinho2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSortearDadinho.setText("Sortear Dadinhos");
        btnSortearDadinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearDadinhoActionPerformed(evt);
            }
        });

        lblDadinho1.setText("Dadinho1: ");

        lblDadinho2.setText("Dadinho2:");

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("     ");

        lblVitoriasDadinho1.setText("Vitorias: 0");

        lblVitoriasDadinho2.setText("Vitorias: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnSortearDadinho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadinho1)
                    .addComponent(lblVitoriasDadinho1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadinho2)
                    .addComponent(lblVitoriasDadinho2))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDadinho1)
                    .addComponent(lblDadinho2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVitoriasDadinho1)
                    .addComponent(lblVitoriasDadinho2))
                .addGap(38, 38, 38)
                .addComponent(btnSortearDadinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortearDadinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearDadinhoActionPerformed
        // TODO add your handling code here:
        Integer valorSorteadoDadinho1 = dadinho1.sortearNumero();
        Integer valorSorteadoDadinho2 = dadinho2.sortearNumero();
        
        lblDadinho1.setText("Dadinho1: "+ valorSorteadoDadinho1);
        lblDadinho2.setText("Dadinho2: "+ valorSorteadoDadinho2);
        
        if(valorSorteadoDadinho1 == valorSorteadoDadinho2){
            lblResultado.setText("Empate");
        }
        else if (valorSorteadoDadinho1>valorSorteadoDadinho2){
            lblResultado.setText("O dadinho1 venceu!");
            vitoriasDadinho1 ++;
            lblVitoriasDadinho1.setText("Vitórias: " + vitoriasDadinho1);
            
        }
        else {
            lblResultado.setText("O dadinho2 venceu!");
            vitoriasDadinho2 ++;
            lblVitoriasDadinho2.setText("Vitórias: " + vitoriasDadinho2);
        }
        
    }//GEN-LAST:event_btnSortearDadinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDadinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDadinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDadinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDadinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDadinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortearDadinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDadinho1;
    private javax.swing.JLabel lblDadinho2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblVitoriasDadinho1;
    private javax.swing.JLabel lblVitoriasDadinho2;
    // End of variables declaration//GEN-END:variables
}
